### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by jerrychong25** [jaimevalero/push-kaggle-dataset#8]
Hi author/maintainer (@jaimevalero),

Today I encountered "**ImportError: cannot import name 'soft_unicode' from 'markupsafe**'" error in GitHub Actions, as per screenshot below:
![image](https://user-images.githubusercontent.com/15714095/154664286-461f6757-3edd-4b59-9b87-2d6f767bcecc.png)

Could help advise how to resolve this error as this is part of GitHub Actions plugin?

For your info, this error does not happened previously.

Thank you.

**Comment by jerrychong25** [comment]
Might related to this issue:
https://github.com/pallets/markupsafe/issues/282
https://github.com/napari/napari/issues/4117

**Comment by jaimevalero** [comment]
Hi @jerrychong25 

Thanks for reporting the bug. 

I have uploaded a [new version](https://github.com/jaimevalero/push-kaggle-dataset/releases/tag/v3),  #9 with the bugfix. 

Please update the github action version to v3, eg:

```yaml
        uses: jaimevalero/push-kaggle-dataset@v3 # This is the action
```

For your convenience, I have done a [PR in your repo](https://github.com/jerrychong25/malaysia-map-data/pull/41) with the bugfix.

**Comment by jerrychong25** [comment]
Hi @jaimevalero ,

Thanks for fixing the bug and created a PR to my repo in https://github.com/jerrychong25/malaysia-map-data.

Your GitHub Action plugin is a great contribution towards Malaysia Open Map Data.

Really appreciated for your great help on this issue!

Cheers,
Jerry Chong
